force-app/main/default/objects/Custom_Quick_Link__mdt/Custom_Quick_Link__mdt.object-meta.xml
<CustomObject>
    <label>Custom Quick Link</label>
    <pluralLabel>Custom Quick Links</pluralLabel>
</CustomObject>

force-app/main/default/objects/Custom_Quick_Link__mdt/fields/Appearance_Order__c.field-meta.xml
<CustomField>
    <fullName>Appearance_Order__c</fullName>
    <label>Appearance Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Quick_Link__mdt/fields/Custom_Quick_Link_Group__c.field-meta.xml
<CustomField>
    <fullName>Custom_Quick_Link_Group__c</fullName>
    <label>Custom Quick Link Group</label>
    <referenceTo>Custom_Quick_Link_Group__mdt</referenceTo>
    <relationshipLabel>Custom Quick Links</relationshipLabel>
    <relationshipName>Custom_Quick_Links</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Custom_Quick_Link__mdt/fields/Display_Record_Count__c.field-meta.xml
<CustomField>
    <fullName>Display_Record_Count__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if &quot;Type&quot; is &quot;Dynamic Single Related List&quot; or &quot;Single Related List&quot; and a record count (0-10+) needs to be displayed alongside the link title. The &quot;Record Count SOQL&quot; field should also be completed to provide a SOQL query that matches the related list parameters.</description>
    <inlineHelpText>Checked if &quot;Type&quot; is &quot;Dynamic Single Related List&quot; or &quot;Single Related List&quot; and a record count (0-10+) needs to be displayed alongside the link title. The &quot;Record Count SOQL&quot; field should also be completed to provide a SOQL query that matches the related list parameters.</inlineHelpText>
    <label>Display Record Count</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Quick_Link__mdt/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Quick_Link__mdt/fields/List_Name__c.field-meta.xml
<CustomField>
    <fullName>List_Name__c</fullName>
    <description>If &quot;Type&quot; is &quot;Dynamic Single Related List&quot;, provide the &quot;cmpId&quot; of the dynamic related list obtained from the list URL (i.e. lst_dynamicRelatedList2, if this was the second dynamic related list that was placed on a flexipage).

If &quot;Type&quot; is &quot;Single Related List&quot;, provide the related list name of the single related list obtained from the list URL (i.e. TLS_Information__r).</description>
    <inlineHelpText>If &quot;Type&quot; is &quot;Dynamic Single Related List&quot;, provide the &quot;cmpId&quot; of the dynamic related list obtained from the list URL (i.e. lst_dynamicRelatedList2, if this was the second dynamic related list that was placed on a flexipage).

If &quot;Type&quot; is &quot;Single Related List&quot;, provide the related list name of the single related list obtained from the list URL (i.e. TLS_Information__r).</inlineHelpText>
    <label>List Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Quick_Link__mdt/fields/Record_Count_SOQL__c.field-meta.xml
<CustomField>
    <fullName>Record_Count_SOQL__c</fullName>
    <description>If &quot;Type&quot; is &quot;Dynamic Single Related List&quot; or &quot;Single Related List&quot; and &quot;Display Record Count&quot; is checked, provide a SOQL query that matches the related list configuration, returns the same number of records as the related list, and includes merge fields in the proper syntax (i.e. SELECT Id FROM Case WHERE AccountId = &apos;[RECORD_ID]&apos;).

Supported merge fields are: [RECORD_ID].</description>
    <inlineHelpText>If &quot;Type&quot; is &quot;Dynamic Single Related List&quot; or &quot;Single Related List&quot; and &quot;Display Record Count&quot; is checked, provide a SOQL query that matches the related list configuration, returns the same number of records as the related list, and includes merge fields in the proper syntax (i.e. SELECT Id FROM Case WHERE AccountId = &apos;[RECORD_ID]&apos;).

Supported merge fields are: [RECORD_ID].</inlineHelpText>
    <label>Record Count SOQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Quick_Link__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Quick_Link__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom Tab (Page)</fullName>
            </value>
            <value>
                <fullName>Dynamic Single Related List</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Single Related List</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Quick_Link__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>If &quot;Type&quot; is &quot;Custom Tab (Page)&quot;, provide the URL beginning after the Salesforce base URL and include merge fields in the proper syntax (i.e. /lightning/n/Relationships?c__recordId=[RECORD_ID]&amp;c__objectType=[OBJECT_API_NAME]).

If &quot;Type&quot; is &quot;External&quot;, provide the full URL of the external site (i.e. https://www.utah.edu).

Supported merge fields are: [RECORD_ID], [RECORD_NAME], [OBJECT_API_NAME].</description>
    <inlineHelpText>If &quot;Type&quot; is &quot;Custom Tab (Page)&quot;, provide the URL beginning after the Salesforce base URL and include merge fields in the proper syntax (i.e. /lightning/n/Relationships?c__recordId=[RECORD_ID]&amp;c__objectType=[OBJECT_API_NAME]).

If &quot;Type&quot; is &quot;External&quot;, provide the full URL of the external site (i.e. https://www.utah.edu).

Supported merge fields are: [RECORD_ID], [RECORD_NAME], [OBJECT_API_NAME].</inlineHelpText>
    <label>URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Quick_Link_Group__mdt/Custom_Quick_Link_Group__mdt.object-meta.xml
<CustomObject>
    <label>Custom Quick Link Group</label>
    <pluralLabel>Custom Quick Links Group</pluralLabel>
</CustomObject>

force-app/main/default/objects/Custom_Quick_Link_Group__mdt/fields/Display_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Display_Record_Types__c</fullName>
    <description>Comma-separated list of record type API names that align with the flexipage listed under the &quot;Assigned Flexipage&quot; field. When the &quot;Custom Quick Links&quot; component is placed on a flexipage (which aligns with these record types) for this object, all child &quot;Custom Quick Link&quot; records will be displayed.</description>
    <inlineHelpText>Comma-separated list of record type API names that align with the flexipage listed under the &quot;Assigned Flexipage&quot; field. When the &quot;Custom Quick Links&quot; component is placed on a flexipage (which aligns with these record types) for this object, all child &quot;Custom Quick Link&quot; records will be displayed.</inlineHelpText>
    <label>Display Record Types</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Quick_Link_Group__mdt/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <description>The API name of the object that will display the custom quick links component.</description>
    <inlineHelpText>The API name of the object that will display the custom quick links component.</inlineHelpText>
    <label>Object Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Account_Group__c</fullName>
            </value>
            <value>
                <fullName>ChangeRequest__c</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Legal_Agreement__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomQuickLinksController.cls
public class CustomQuickLinksController {

	@AuraEnabled(cacheable=true)
	public static List<Custom_Quick_Link__mdt> getCustomQuickLinks(String recordId, String objectApiName, String recordTypeDevName) {
		List<Custom_Quick_Link__mdt> quickLinks = new List<Custom_Quick_Link__mdt>();
		List<Custom_Quick_Link_Group__mdt> quickLinkGrps = new List<Custom_Quick_Link_Group__mdt>([SELECT Id, Display_Record_Types__c, Object_Type__c
																									FROM Custom_Quick_Link_Group__mdt
																									WHERE Object_Type__c = :objectApiName]);
		if (quickLinkGrps.size() > 0) {
			// Evaluate and remove any quick link group records that that are unavailable to this record type.
			for (Integer i = quickLinkGrps.size()-1; i >= 0; i--) { // NOTE: Loop backwards to account for changing index number when a value is identified and removed.
				Boolean matchingRecordType = false;
				List<String> splitObjectType = quickLinkGrps[i]?.Display_Record_Types__c?.split(', ');
				if (splitObjectType.contains(recordTypeDevName)) {
					matchingRecordType = true;
				}
				if (!matchingRecordType) {
					quickLinkGrps.remove(i);
				}
			}
			if (quickLinkGrps.size() > 0) { // Only one quick link group should remain for each object/record type combo (although there is no way to enforce this with a CMT validation rule)...
				Custom_Quick_Link_Group__mdt cqlg = quickLinkGrps[0]; //...so always assume the first is that only one.
				quickLinks = [SELECT Id, Appearance_Order__c, Custom_Quick_Link_Group__c, Display_Record_Count__c, Icon__c, Label,
								List_Name__c, Record_Count_SOQL__c, Title__c, Type__c, URL__c
								FROM Custom_Quick_Link__mdt
								WHERE Custom_Quick_Link_Group__c = :cqlg.Id
								ORDER BY Appearance_Order__c];
			}
		}
		return quickLinks;
	}

	@AuraEnabled(cacheable=true)
	public static Integer getCustomQuickLinkRecordCount(String queryString) {
		List<sObject> records = Database.query(queryString);
		Integer recordCount = records.size();
		return recordCount;
	}
}